#include "sp_tools_common.h"
#include "ext/zstd.h"
#include <assert.h>
#include <string.h>

const sp_format_info sp_format_infos[SP_FORMAT_COUNT] = {
	{ SP_FORMAT_UNKNOWN, "SP_FORMAT_UNKNOWN", "(unknown)", 0, 0, 0, 0, 0 },
	{ SP_FORMAT_R8_UNORM, "SP_FORMAT_R8_UNORM", "r8", 1, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R8_SNORM, "SP_FORMAT_R8_SNORM", "r8sn", 1, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R8_UINT, "SP_FORMAT_R8_UINT", "r8u", 1, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R8_SINT, "SP_FORMAT_R8_SINT", "r8i", 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG8_UNORM, "SP_FORMAT_RG8_UNORM", "rg8", 2, 2, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG8_SNORM, "SP_FORMAT_RG8_SNORM", "rg8sn", 2, 2, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG8_UINT, "SP_FORMAT_RG8_UINT", "rg8u", 2, 2, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG8_SINT, "SP_FORMAT_RG8_SINT", "rg8i", 2, 2, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB8_UNORM, "SP_FORMAT_RGB8_UNORM", "rgb8", 3, 3, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB8_SNORM, "SP_FORMAT_RGB8_SNORM", "rgb8sn", 3, 3, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB8_UINT, "SP_FORMAT_RGB8_UINT", "rgb8u", 3, 3, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB8_SINT, "SP_FORMAT_RGB8_SINT", "rgb8i", 3, 3, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB8_SRGB, "SP_FORMAT_RGB8_SRGB", "rgb8_srgb", 3, 3, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_RGBA8_UNORM, "SP_FORMAT_RGBA8_UNORM", "rgba8", 4, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA8_SNORM, "SP_FORMAT_RGBA8_SNORM", "rgba8sn", 4, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA8_UINT, "SP_FORMAT_RGBA8_UINT", "rgba8u", 4, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA8_SINT, "SP_FORMAT_RGBA8_SINT", "rgba8i", 4, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA8_SRGB, "SP_FORMAT_RGBA8_SRGB", "rgba8_srgb", 4, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_R16_UNORM, "SP_FORMAT_R16_UNORM", "r16", 1, 2, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R16_SNORM, "SP_FORMAT_R16_SNORM", "r16sn", 1, 2, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R16_UINT, "SP_FORMAT_R16_UINT", "r16u", 1, 2, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R16_SINT, "SP_FORMAT_R16_SINT", "r16i", 1, 2, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R16_FLOAT, "SP_FORMAT_R16_FLOAT", "r16f", 1, 2, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG16_UNORM, "SP_FORMAT_RG16_UNORM", "rg16", 2, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG16_SNORM, "SP_FORMAT_RG16_SNORM", "rg16sn", 2, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG16_UINT, "SP_FORMAT_RG16_UINT", "rg16u", 2, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG16_SINT, "SP_FORMAT_RG16_SINT", "rg16i", 2, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG16_FLOAT, "SP_FORMAT_RG16_FLOAT", "rg16f", 2, 4, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB16_UNORM, "SP_FORMAT_RGB16_UNORM", "rgb16", 3, 6, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB16_SNORM, "SP_FORMAT_RGB16_SNORM", "rgb16sn", 3, 6, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB16_UINT, "SP_FORMAT_RGB16_UINT", "rgb16u", 3, 6, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB16_SINT, "SP_FORMAT_RGB16_SINT", "rgb16i", 3, 6, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB16_FLOAT, "SP_FORMAT_RGB16_FLOAT", "rgb16f", 3, 6, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA16_UNORM, "SP_FORMAT_RGBA16_UNORM", "rgba16", 4, 8, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA16_SNORM, "SP_FORMAT_RGBA16_SNORM", "rgba16sn", 4, 8, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA16_UINT, "SP_FORMAT_RGBA16_UINT", "rgba16u", 4, 8, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA16_SINT, "SP_FORMAT_RGBA16_SINT", "rgba16i", 4, 8, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA16_FLOAT, "SP_FORMAT_RGBA16_FLOAT", "rgba16f", 4, 8, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R32_UNORM, "SP_FORMAT_R32_UNORM", "r32", 1, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R32_SNORM, "SP_FORMAT_R32_SNORM", "r32sn", 1, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R32_UINT, "SP_FORMAT_R32_UINT", "r32u", 1, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R32_SINT, "SP_FORMAT_R32_SINT", "r32i", 1, 4, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_R32_FLOAT, "SP_FORMAT_R32_FLOAT", "r32f", 1, 4, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG32_UNORM, "SP_FORMAT_RG32_UNORM", "rg32", 2, 8, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG32_SNORM, "SP_FORMAT_RG32_SNORM", "rg32sn", 2, 8, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG32_UINT, "SP_FORMAT_RG32_UINT", "rg32u", 2, 8, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG32_SINT, "SP_FORMAT_RG32_SINT", "rg32i", 2, 8, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RG32_FLOAT, "SP_FORMAT_RG32_FLOAT", "rg32f", 2, 8, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB32_UNORM, "SP_FORMAT_RGB32_UNORM", "rgb32", 3, 12, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB32_SNORM, "SP_FORMAT_RGB32_SNORM", "rgb32sn", 3, 12, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB32_UINT, "SP_FORMAT_RGB32_UINT", "rgb32u", 3, 12, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB32_SINT, "SP_FORMAT_RGB32_SINT", "rgb32i", 3, 12, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGB32_FLOAT, "SP_FORMAT_RGB32_FLOAT", "rgb32f", 3, 12, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA32_UNORM, "SP_FORMAT_RGBA32_UNORM", "rgba32", 4, 16, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA32_SNORM, "SP_FORMAT_RGBA32_SNORM", "rgba32sn", 4, 16, 1, 1, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA32_UINT, "SP_FORMAT_RGBA32_UINT", "rgba32u", 4, 16, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA32_SINT, "SP_FORMAT_RGBA32_SINT", "rgba32i", 4, 16, 1, 1, SP_FORMAT_FLAG_INTEGER|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_RGBA32_FLOAT, "SP_FORMAT_RGBA32_FLOAT", "rgba32f", 4, 16, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED|SP_FORMAT_FLAG_BASIC },
	{ SP_FORMAT_D16_UNORM, "SP_FORMAT_D16_UNORM", "d16", 1, 2, 1, 1, SP_FORMAT_FLAG_DEPTH },
	{ SP_FORMAT_D24S8_UNORM, "SP_FORMAT_D24S8_UNORM", "d24s8", 1, 4, 1, 1, SP_FORMAT_FLAG_DEPTH|SP_FORMAT_FLAG_STENCIL },
	{ SP_FORMAT_D32_FLOAT, "SP_FORMAT_D32_FLOAT", "d32f", 1, 4, 1, 1, SP_FORMAT_FLAG_DEPTH },
	{ SP_FORMAT_D32S8_FLOAT, "SP_FORMAT_D32S8_FLOAT", "d32s8f", 1, 8, 1, 1, SP_FORMAT_FLAG_DEPTH|SP_FORMAT_FLAG_STENCIL },
	{ SP_FORMAT_RGB10A2_UNORM, "SP_FORMAT_RGB10A2_UNORM", "rgb10a2", 4, 4, 1, 1, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_RGB10A2_UINT, "SP_FORMAT_RGB10A2_UINT", "rgb10a2u", 4, 4, 1, 1, SP_FORMAT_FLAG_INTEGER },
	{ SP_FORMAT_R11G11B10_FLOAT, "SP_FORMAT_R11G11B10_FLOAT", "r11g11b10f", 3, 4, 1, 1, SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED },
	{ SP_FORMAT_BC1_UNORM, "SP_FORMAT_BC1_UNORM", "bc1", 4, 8, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC1_SRGB, "SP_FORMAT_BC1_SRGB", "bc1_srgb", 4, 8, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_BC2_UNORM, "SP_FORMAT_BC2_UNORM", "bc2", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC2_SRGB, "SP_FORMAT_BC2_SRGB", "bc2_srgb", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_BC3_UNORM, "SP_FORMAT_BC3_UNORM", "bc3", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC3_SRGB, "SP_FORMAT_BC3_SRGB", "bc3_srgb", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_BC4_UNORM, "SP_FORMAT_BC4_UNORM", "bc4", 1, 8, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC4_SNORM, "SP_FORMAT_BC4_SNORM", "bc4sn", 1, 8, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED },
	{ SP_FORMAT_BC5_UNORM, "SP_FORMAT_BC5_UNORM", "bc5", 2, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC5_SNORM, "SP_FORMAT_BC5_SNORM", "bc5sn", 2, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SIGNED },
	{ SP_FORMAT_BC6_UFLOAT, "SP_FORMAT_BC6_UFLOAT", "bc6_ufloat", 3, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_FLOAT },
	{ SP_FORMAT_BC6_SFLOAT, "SP_FORMAT_BC6_SFLOAT", "bc6_sfloat", 3, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_FLOAT|SP_FORMAT_FLAG_SIGNED },
	{ SP_FORMAT_BC7_UNORM, "SP_FORMAT_BC7_UNORM", "bc7", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_BC7_SRGB, "SP_FORMAT_BC7_SRGB", "bc7_srgb", 4, 16, 4, 4, SP_FORMAT_FLAG_COMPRESSED|SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC4X4_UNORM, "SP_FORMAT_ASTC4X4_UNORM", "astc4x4", 4, 16, 4, 4, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC4X4_SRGB, "SP_FORMAT_ASTC4X4_SRGB", "astc4x4_srgb", 4, 16, 4, 4, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC5X4_UNORM, "SP_FORMAT_ASTC5X4_UNORM", "astc5x4", 4, 16, 5, 4, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC5X4_SRGB, "SP_FORMAT_ASTC5X4_SRGB", "astc5x4_srgb", 4, 16, 5, 4, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC5X5_UNORM, "SP_FORMAT_ASTC5X5_UNORM", "astc5x5", 4, 16, 5, 5, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC5X5_SRGB, "SP_FORMAT_ASTC5X5_SRGB", "astc5x5_srgb", 4, 16, 5, 5, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC6X5_UNORM, "SP_FORMAT_ASTC6X5_UNORM", "astc6x5", 4, 16, 6, 5, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC6X5_SRGB, "SP_FORMAT_ASTC6X5_SRGB", "astc6x5_srgb", 4, 16, 6, 5, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC6X6_UNORM, "SP_FORMAT_ASTC6X6_UNORM", "astc6x6", 4, 16, 6, 6, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC6X6_SRGB, "SP_FORMAT_ASTC6X6_SRGB", "astc6x6_srgb", 4, 16, 6, 6, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC8X5_UNORM, "SP_FORMAT_ASTC8X5_UNORM", "astc8x5", 4, 16, 8, 5, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC8X5_SRGB, "SP_FORMAT_ASTC8X5_SRGB", "astc8x5_srgb", 4, 16, 8, 5, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC8X6_UNORM, "SP_FORMAT_ASTC8X6_UNORM", "astc8x6", 4, 16, 8, 6, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC8X6_SRGB, "SP_FORMAT_ASTC8X6_SRGB", "astc8x6_srgb", 4, 16, 8, 6, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC10X5_UNORM, "SP_FORMAT_ASTC10X5_UNORM", "astc10x5", 4, 16, 10, 5, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC10X5_SRGB, "SP_FORMAT_ASTC10X5_SRGB", "astc10x5_srgb", 4, 16, 10, 5, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC10X6_UNORM, "SP_FORMAT_ASTC10X6_UNORM", "astc10x6", 4, 16, 10, 6, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC10X6_SRGB, "SP_FORMAT_ASTC10X6_SRGB", "astc10x6_srgb", 4, 16, 10, 6, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC8X8_UNORM, "SP_FORMAT_ASTC8X8_UNORM", "astc8x8", 4, 16, 8, 8, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC8X8_SRGB, "SP_FORMAT_ASTC8X8_SRGB", "astc8x8_srgb", 4, 16, 8, 8, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC10X8_UNORM, "SP_FORMAT_ASTC10X8_UNORM", "astc10x8", 4, 16, 10, 8, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC10X8_SRGB, "SP_FORMAT_ASTC10X8_SRGB", "astc10x8_srgb", 4, 16, 10, 8, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC10X10_UNORM, "SP_FORMAT_ASTC10X10_UNORM", "astc10x10", 4, 16, 10, 10, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC10X10_SRGB, "SP_FORMAT_ASTC10X10_SRGB", "astc10x10_srgb", 4, 16, 10, 10, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC12X10_UNORM, "SP_FORMAT_ASTC12X10_UNORM", "astc12x10", 4, 16, 12, 10, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC12X10_SRGB, "SP_FORMAT_ASTC12X10_SRGB", "astc12x10_srgb", 4, 16, 12, 10, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
	{ SP_FORMAT_ASTC12X12_UNORM, "SP_FORMAT_ASTC12X12_UNORM", "astc12x12", 4, 16, 12, 12, SP_FORMAT_FLAG_NORMALIZED },
	{ SP_FORMAT_ASTC12X12_SRGB, "SP_FORMAT_ASTC12X12_SRGB", "astc12x12_srgb", 4, 16, 12, 12, SP_FORMAT_FLAG_NORMALIZED|SP_FORMAT_FLAG_SRGB },
};

sp_format sp_find_format(uint32_t num_components, uint32_t component_size, sp_format_flags flags)
{
	uint32_t key = component_size << 4 | num_components;
	if (flags & SP_FORMAT_FLAG_FLOAT) {
		switch (key) {
		case 0x11: return SP_FORMAT_UNKNOWN;
		case 0x12: return SP_FORMAT_UNKNOWN;
		case 0x13: return SP_FORMAT_UNKNOWN;
		case 0x14: return SP_FORMAT_UNKNOWN;
		case 0x21: return SP_FORMAT_R16_FLOAT;
		case 0x22: return SP_FORMAT_RG16_FLOAT;
		case 0x23: return SP_FORMAT_RGB16_FLOAT;
		case 0x24: return SP_FORMAT_RGBA16_FLOAT;
		case 0x41: return SP_FORMAT_R32_FLOAT;
		case 0x42: return SP_FORMAT_RG32_FLOAT;
		case 0x43: return SP_FORMAT_RGB32_FLOAT;
		case 0x44: return SP_FORMAT_RGBA32_FLOAT;
		default: return SP_FORMAT_UNKNOWN;
		}
	} else if (flags & SP_FORMAT_FLAG_NORMALIZED) {
		if (flags & SP_FORMAT_FLAG_SIGNED) {
			switch (key) {
			case 0x11: return SP_FORMAT_R8_SNORM;
			case 0x12: return SP_FORMAT_RG8_SNORM;
			case 0x13: return SP_FORMAT_RGB8_SNORM;
			case 0x14: return SP_FORMAT_RGBA8_SNORM;
			case 0x21: return SP_FORMAT_R16_SNORM;
			case 0x22: return SP_FORMAT_RG16_SNORM;
			case 0x23: return SP_FORMAT_RGB16_SNORM;
			case 0x24: return SP_FORMAT_RGBA16_SNORM;
			case 0x41: return SP_FORMAT_R32_SNORM;
			case 0x42: return SP_FORMAT_RG32_SNORM;
			case 0x43: return SP_FORMAT_RGB32_SNORM;
			case 0x44: return SP_FORMAT_RGBA32_SNORM;
			default: return SP_FORMAT_UNKNOWN;
			}
		} else {
			switch (key) {
			case 0x11: return SP_FORMAT_R8_UNORM;
			case 0x12: return SP_FORMAT_RG8_UNORM;
			case 0x13: return SP_FORMAT_RGB8_UNORM;
			case 0x14: return SP_FORMAT_RGBA8_UNORM;
			case 0x21: return SP_FORMAT_R16_UNORM;
			case 0x22: return SP_FORMAT_RG16_UNORM;
			case 0x23: return SP_FORMAT_RGB16_UNORM;
			case 0x24: return SP_FORMAT_RGBA16_UNORM;
			case 0x41: return SP_FORMAT_R32_UNORM;
			case 0x42: return SP_FORMAT_RG32_UNORM;
			case 0x43: return SP_FORMAT_RGB32_UNORM;
			case 0x44: return SP_FORMAT_RGBA32_UNORM;
			default: return SP_FORMAT_UNKNOWN;
			}
		}
	} else if (flags & SP_FORMAT_FLAG_INTEGER) {
		if (flags & SP_FORMAT_FLAG_SIGNED) {
			switch (key) {
			case 0x11: return SP_FORMAT_R8_SINT;
			case 0x12: return SP_FORMAT_RG8_SINT;
			case 0x13: return SP_FORMAT_RGB8_SINT;
			case 0x14: return SP_FORMAT_RGBA8_SINT;
			case 0x21: return SP_FORMAT_R16_SINT;
			case 0x22: return SP_FORMAT_RG16_SINT;
			case 0x23: return SP_FORMAT_RGB16_SINT;
			case 0x24: return SP_FORMAT_RGBA16_SINT;
			case 0x41: return SP_FORMAT_R32_SINT;
			case 0x42: return SP_FORMAT_RG32_SINT;
			case 0x43: return SP_FORMAT_RGB32_SINT;
			case 0x44: return SP_FORMAT_RGBA32_SINT;
			default: return SP_FORMAT_UNKNOWN;
			}
		} else {
			switch (key) {
			case 0x11: return SP_FORMAT_R8_UINT;
			case 0x12: return SP_FORMAT_RG8_UINT;
			case 0x13: return SP_FORMAT_RGB8_UINT;
			case 0x14: return SP_FORMAT_RGBA8_UINT;
			case 0x21: return SP_FORMAT_R16_UINT;
			case 0x22: return SP_FORMAT_RG16_UINT;
			case 0x23: return SP_FORMAT_RGB16_UINT;
			case 0x24: return SP_FORMAT_RGBA16_UINT;
			case 0x41: return SP_FORMAT_R32_UINT;
			case 0x42: return SP_FORMAT_RG32_UINT;
			case 0x43: return SP_FORMAT_RGB32_UINT;
			case 0x44: return SP_FORMAT_RGBA32_UINT;
			default: return SP_FORMAT_UNKNOWN;
			}
		}
	}
	return SP_FORMAT_UNKNOWN;
}

size_t sp_get_compression_bound(sp_compression_type type, size_t src_size)
{
	switch (type)
	{
	case SP_COMPRESSION_NONE: return src_size;
	case SP_COMPRESSION_ZSTD: return ZSTD_compressBound(src_size);
	default: return 0;
	}
}

size_t sp_compress_buffer(sp_compression_type type, void *dst, size_t dst_size, const void *src, size_t src_size, int level)
{
	if (level < 1) level = 1;
	if (level > 20) level = 20;
	switch (type)
	{
	case SP_COMPRESSION_NONE:
		assert(dst_size >= src_size);
		memcpy(dst, src, src_size);
		return src_size;
	case SP_COMPRESSION_ZSTD:
		return ZSTD_compress(dst, dst_size, src, src_size, level - 1);
	default: return 0;
	}
}

size_t sp_decompress_buffer(sp_compression_type type, void *dst, size_t dst_size, const void *src, size_t src_size)
{
	switch (type)
	{
	case SP_COMPRESSION_NONE:
		assert(dst_size >= src_size);
		memcpy(dst, src, src_size);
		return src_size;
	case SP_COMPRESSION_ZSTD:
		return ZSTD_decompress(dst, dst_size, src, src_size);
	default: return 0;
	}
}

